web:
  build: .
  command: php -S 0.0.0.0:8000 -t /code/wordpress
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/code
db:
  image: orchardup/mysql
  volumes:
    - db_data:/var/lib/mysql
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - db:mysql
  ports:
    - "8100:80"
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass