web:
  build: .
  command: php -S 0.0.0.0:8000 -t /code/wordpress
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/code
wordpress_db:
  image: mariadb
  volumes:
      - ./db_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - "8100:80"
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass