wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - "8000:80"
  volumes:
      - ./wordpress:/var/www/html
wordpress_db:
  image: mariadb
  volumes:
      - ./db_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: examplepass
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - "8100:80"
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: examplepass